### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by a-sp** [mikestreety/pypi-lcdscreen#1]
Hi @mikestreety, first of all, thank you for sharing your LCD Screen Python Class, I really like it 😊

I've tried example.py with my LCD 20x4 (controller KS0066, basically identical to HD44780) connected to an RPi 3 B. 

Everything seems to work properly, all the messages are shown correctly on the LCD, but every time I run the script, my ssh connection freezes and I need to manually power the RPi off by detaching the USB power supply. 

This issue does not occur when I run any other script (which interact with the LCD), without using your class. 

Any ideas?

**Comment by mikestreety** [comment]
Hey @a-sp - thanks so much for the issue. 

Unfortunately this code is 5 years old - I suspect a lot of things have changed since I wrote this and I no longer play with screens and RPis at the moment, so I don't have the time/resources/motivation to look into this.

I'm so sorry, I hope you find another way of using your LCD - would happily accept a merge request if you find the solution!

Good luck :)
